repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c '.venv/bin/pip3 freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
      - id: mypy
        name: mypy
        entry: "mypy --explicit-package-bases --ignore-missing-imports"
        language: python
        language_version: python3.12
        additional_dependencies: ["mypy==1.11.1"]
        types: [python]
        require_serial: true
        verbose: true